version: "3.7"

services:
  app_proxy:
    environment:
      # <app-id>_<web-container-name>_1
      # e.g. 'btc-rpc-explorer_web_1'
      # Note that the '_1' at the end is needed
      APP_HOST: topl-bifrost-node_web_1
      APP_PORT: 8080
      PROXY_TRUST_UPSTREAM: "true"
      LOG_LEVEL: "debug"
      PROXY_AUTH_ADD: "false"
  
  web:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
  
  node:
    image: toplprotocol/bifrost-node:2.0.0-alpha2
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 9085:9085
      - 9084:9084
    volumes: []
    environment: []
  # If your app has more services, like a database container, you can define those
  # services below:
  # db:
  #   image: <docker-image>:<tag>
  #   ...
